### ISSUE TITLE
"Install Privacy Badger" button should include the current browser name/logo

### ISSUE THREAD

**Issue by nickfrostatx** [EFForg/privacybadger-website#19]
If you visit the home page on Chrome, it looks like Privacy Badger only supports Opera, Firefox, and Firefox on Android. When I first loaded the page, I went back to my search engine and looked up "privacy badger chrome".

The text in the button should indicate that it's actually a link to the Chrome web store.

Here's what I saw when I first viewed the page:

<img width="1020" alt="Screen Shot 2019-07-18 at 10 33 31 AM" src="https://user-images.githubusercontent.com/839071/61478902-8293b080-a947-11e9-9aab-836642b9ace9.png">

**Comment by pipboy96** [comment]
I'll try implementing this.

**Comment by pipboy96** [comment]
Maybe we should just move other browsers into a collapsible called "Other browsers" instead?

**Comment by andresbase** [comment]
This is a really good point, thanks for noticing this! 

I think others should be clearly visible, it allows people see where PB is available without having to click anything.

For the install button I'm unsure where the logo and name of the current browser should be shows but would love to see suggestions.

**Comment by ghostwords** [comment]
@wioux Any thoughts about this? I've gotten multiple support requests from confused users over time.

I think the highest priority enhancement is to make the big install button consistent with the lesser buttons by adding the browser name/logo. We can follow up with other tweaks later.
