### ISSUE TITLE
Implement language switcher

### ISSUE THREAD

**Issue by lenazun** [EFForg/privacybadger-website#28]
There's currently no language switcher in the page! We should add the switcher and make sure only the content with the selected locale shows up.

I believe we could make a partial with the [list of translated content](https://gohugo.io/content-management/multilingual/#reference-the-translated-content) and style it as a dropdown, maybe?

The Let's encrypt website has a nice example [here](https://discourse.gohugo.io/t/language-switcher-in-menu/11570/4).

**Comment by andresbase** [comment]
Yes that would be ideal thanks!

<img width="240" alt="Screen Shot 2019-10-16 at 19 41 46" src="https://user-images.githubusercontent.com/1775039/66968947-0c3d4200-f04d-11e9-9006-881eeb1c2efc.png">

**Comment by wioux** [comment]
How many languages are we including? Since there's only one alternative at the moment I just added a link to it in #30. I think listing them out like that will work well if there are just 2-3, but if more translations are coming I can go ahead and make that a dropdown.

**Comment by andresbase** [comment]
There will be more translations. We're hopping a min of 7 languages.

**Comment by andresbase** [comment]
Language switcher added in #30
