### ISSUE TITLE
Update FAQ anchor links on new site to match old site to avoid breaking existing deep links

### ISSUE THREAD

**Issue by andresbase** [EFForg/privacybadger-website#32]
For example https://privacybadger-staging.d5.eff.org/#How-to-uninstall

and 

    new: https://privacybadger-staging.d5.eff.org/#what-is-pb
    current: https://www.eff.org/privacybadger/faq#What-is-Privacy-Badger

**Comment by ghostwords** [comment]
A few anchors still do not match:

```
#Will-you-be-supporting-any-other-browsers-besides-Chrome-/-Firefox-/-Opera
#-I-am-an-online-advertising-/-tracking-company.--How-do-I-stop-Privacy-Badger-from-blocking-me
#How-do-I-uninstall/remove-Privacy-Badger
```

**Comment by ghostwords** [comment]
Reopening, still an issue: https://github.com/EFForg/privacybadger-website/pull/54#issuecomment-606050659
