### ISSUE TITLE
Squished layout on mobile

### ISSUE THREAD

**Issue by andresbase** [EFForg/privacybadger-website#33]
On mobile the site looks squished on chrome.

**Comment by ghostwords** [comment]
This is with device simulation in Chrome dev tools though, haven't checked on an actual Android device yet.

Screenshot:
![Screenshot from 2019-12-04 18:45:45](https://user-images.githubusercontent.com/794578/70191337-6ad68200-16c6-11ea-908b-7b94fe4e0b59.png)
