### ISSUE TITLE
FAQ redirection not implemented on the new website?

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger-website#36]
To avoid breaking existing links, we need to support people visiting `/faq` as well as deep links within `/faq` ([for example](https://www.eff.org/privacybadger/faq#Does-Privacy-Badger-still-work-when-blocking-third-party-cookies-in-the-browser)).

We also currently have redirection in place for people visiting the old anchor format. Not sure we need to preserve that logic, but would be nice if we do, I suppose. To see (all of? some of?) this logic, look for `FaqRedirects` in https://www.eff.org/files/js/js_IFIFC6BlKVHfvxT8x04aRoX9DmTIfKSEHjVCinGETws.js

Related to #32.

**Comment by andresbase** [comment]
It seems to be working now after #32

**Comment by ghostwords** [comment]
What do you mean? Going to `/faq` on staging does not redirect for me (I get a 404).

**Comment by ablanathtanalba** [comment]
on the production build right now, the FAQ section lives on the front page. I think that nullifies this issue, right?

On the other hand, for some reason the hugo dev build doesn't load the FAQ content at all: 

![Screenshot from 2020-03-26 08-54-40](https://user-images.githubusercontent.com/25778052/77667491-81d40500-6f3f-11ea-8d36-da36006e77b8.png)

**Comment by ghostwords** [comment]
> on the production build right now, the FAQ section lives on the front page. I think that nullifies this issue, right?

To clarify, we need to keep existing links working. So, links like https://privacybadger.org/faq#How-to-uninstall need to continue to function.

**Comment by ghostwords** [comment]
For example, the Privacy Badger popup links to https://www.eff.org/privacybadger#faq-What-is-a-third-party-tracker?. This is broken right now.

**Comment by ghostwords** [comment]
Reopening, still an issue: https://github.com/EFForg/privacybadger-website/pull/54#issuecomment-606050659
