### ISSUE TITLE
Does the Badger version autoupdate on the new website?

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger-website#37]
As it does on the current site.

The new site is showing `v2019.2.19` whereas prod correctly auto-updated to show `v2019.11.18`.

**Comment by andresbase** [comment]
@wioux do you know if this is specific to the staging or did something break along the way?

**Comment by wioux** [comment]
No, the version number is read out of config.toml and at the moment has to be manually bumped:

https://github.com/EFForg/privacybadger-website/blob/01f4a11e00647ca854f67856d443e8f18286ffef/config.toml#L5-L6

**Comment by ghostwords** [comment]
Could we carry over version autoupdate logic from the existing website (to reduce the number of manual per-release tasks)?

**Comment by ablanathtanalba** [comment]
Looks like #42 took care of this issue but it didn't automatically close it. :sparkles:
